"""DeepSeek V3.2 Training Module"""

from .grpo import GRPOTrainer, GroupSampler
from .optimization import (
    CompileMode,
    CompileConfig,
    compile_model,
    create_compile_warmup_wrapper,
    PrecisionMode,
    MixedPrecisionConfig,
    MixedPrecisionTrainer,
    get_optimal_precision,
    supports_bfloat16,
    supports_fp16,
    MemoryStats,
    MemoryProfiler,
    create_pytorch_profiler,
    calculate_mbu,
    # Phase 1 additions
    NaNCheckResult,
    check_nan_inf,
    NaNInfValidator,
    MemoryBudgetConfig,
    MemoryBudgetManager,
    measure_compilation_overhead,
    # Additional Phase 1 classes
    PrecisionWeightInitializer,
    NumericalValidator,
    CPUOffloadConfig,
    GradientAccumulationConfig,
    GradientAccumulationContext,
    create_gradient_accumulation_context,
)
from .agent import (
    ToolType,
    ToolStatus,
    ToolCall,
    ToolResponse,
    AgentActionType,
    AgentAction,
    AgentStep,
    AgentTrajectory,
    TaskTier,
    RewardWeights,
    RewardBreakdown,
    AgentRewardComputer,
    TaskTemplate,
    TaskGenerator,
    AgentEnvironment,
    AgentGRPOConfig,
    AgentGRPOTrainer,
    ToolCallParser,
    AgentGroupSampler,
    create_agent_trainer,
    compute_agent_reward,
)

__all__ = [
    # GRPO
    "GRPOTrainer",
    "GroupSampler",
    # Optimization (Phase 1)
    "CompileMode",
    "CompileConfig",
    "compile_model",
    "create_compile_warmup_wrapper",
    "PrecisionMode",
    "MixedPrecisionConfig",
    "MixedPrecisionTrainer",
    "get_optimal_precision",
    "supports_bfloat16",
    "supports_fp16",
    "MemoryStats",
    "MemoryProfiler",
    "create_pytorch_profiler",
    "calculate_mbu",
    # Phase 1 additions
    "NaNCheckResult",
    "check_nan_inf",
    "NaNInfValidator",
    "MemoryBudgetConfig",
    "MemoryBudgetManager",
    "measure_compilation_overhead",
    # Additional Phase 1 classes
    "PrecisionWeightInitializer",
    "NumericalValidator",
    "CPUOffloadConfig",
    "GradientAccumulationConfig",
    "GradientAccumulationContext",
    "create_gradient_accumulation_context",
    # Agent Training
    "ToolType",
    "ToolStatus", 
    "ToolCall",
    "ToolResponse",
    "AgentActionType",
    "AgentAction",
    "AgentStep",
    "AgentTrajectory",
    "TaskTier",
    "RewardWeights",
    "RewardBreakdown",
    "AgentRewardComputer",
    "TaskTemplate",
    "TaskGenerator",
    "AgentEnvironment",
    "AgentGRPOConfig",
    "AgentGRPOTrainer",
    "ToolCallParser",
    "AgentGroupSampler",
    "create_agent_trainer",
    "compute_agent_reward",
]
